// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMstIxcukG2N7Av63Qfz0ap1tje2_koLQ',
    appId: '1:714258713388:web:af08b827221ba31f6f3a89',
    messagingSenderId: '714258713388',
    projectId: 'taskify-task-mgmt',
    authDomain: 'taskify-task-mgmt.firebaseapp.com',
    storageBucket: 'taskify-task-mgmt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXw6pmuoANCvneyGsc6cqbpqihuN4k-g',
    appId: '1:714258713388:android:d7cac4359e97b5686f3a89',
    messagingSenderId: '714258713388',
    projectId: 'taskify-task-mgmt',
    storageBucket: 'taskify-task-mgmt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-LLsWDCE8LNNG-_-v0l61u5SRalLhns',
    appId: '1:714258713388:ios:57987f2822e7d64a6f3a89',
    messagingSenderId: '714258713388',
    projectId: 'taskify-task-mgmt',
    storageBucket: 'taskify-task-mgmt.appspot.com',
    iosClientId: '714258713388-3baie4vl19dtnsq12ief6ch3t1cjrkbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-LLsWDCE8LNNG-_-v0l61u5SRalLhns',
    appId: '1:714258713388:ios:e7e0a7078af078376f3a89',
    messagingSenderId: '714258713388',
    projectId: 'taskify-task-mgmt',
    storageBucket: 'taskify-task-mgmt.appspot.com',
    iosClientId: '714258713388-5cmrac82s3efetd0v9kb9dt0pq1ncngs.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskify.RunnerTests',
  );
}
